name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        with:
          php_version: 8.0
          php_extensions: apcu

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          php_extensions: apcu
          args: --coverage-text
        env:
          TEST_NAME: TPCentre
